/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import business.saveList;
import data.Animal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrien
 */
public class PetStoreGUI extends javax.swing.JFrame implements UI{

    boolean flag = false;
    ArrayList<Integer> selectionTable = new ArrayList<>();
    /**
     * Creates new form PetStoreGUI
     */
    public PetStoreGUI() {
        try{
        initComponents();
        this.pack();
        this.setVisible(true);
        }
        catch(Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelo=new DefaultListModel();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 252, 25));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 252, 25));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(178, 18, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Please select one or more animals to show their informations. <br/>You can also select the save Option to export the shop.</html>");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(255, 252, 25));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(178, 18, 18));
        jButton1.setText("OK");
        jButton1.setActionCommand("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 252, 25));
        jScrollPane1.setBorder(null);

        jList1.setModel(modelo);
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) jList1.getCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jList1.setBackground(new java.awt.Color(255, 252, 25));
        jList1.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        jList1.setForeground(new java.awt.Color(20, 133, 204));
        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        jButton2.setBackground(new java.awt.Color(255, 252, 25));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(178, 18, 18));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectionTable.clear();
        int[] tempList=jList1.getSelectedIndices();
        for(int i=0; i<tempList.length;i++) {
            selectionTable.add(tempList[i]);
        }
        flag=false;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       saveList.save();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetStoreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetStoreGUI().setVisible(true);
            }
        });
    }

    @Override
    public void printPet(Animal pet) {
        JOptionPane.showMessageDialog(this,pet.toString());
    }

    @Override
    public void printFileCreation() {
        JOptionPane.showMessageDialog(this,"The save file wasn't found, the default configuration was load.");
    }

    @Override
    public void sayWelcome() {
        JOptionPane.showMessageDialog(this,"Welcolme to our fabulous PetShop !");
    }

    @Override
    public void pause() {
        
    }
    
    private void waitEntry() {
        flag=true;
        while(flag==true) {
            try {
                Thread.sleep(50);
            } catch (InterruptedException ex) {
            }
        }
    }

    @Override
    public void sayGoodBy() {
        JOptionPane.showMessageDialog(this,"We hope that you enjoyed our PetShop, see you soon ! ;-)");
    }

    @Override
    public void printMenuMyt(ArrayList<Animal> animalList) {
        modelo.clear();
        for (int i=0; i<animalList.size();i++){
            modelo.addElement(animalList.get(i).getName());
        }
        
        waitEntry();
    }

    @Override
    public ArrayList<Integer> askIntMyt(int maxInt) {
        return selectionTable;
    }

    @Override
    public boolean askQuit() {
        Object[] options = {"Continue","Quit"};
        int n = JOptionPane.showOptionDialog(this, "Do you want to quit the App or search for new pets ?", "Question",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,options, options[1]);
        if(n==1) {
            return false;
        }
        else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private DefaultListModel modelo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
